// Master skill list for dropdowns and validation
export const SKILL_LIST = [
  'Java',
  'C++',
  'Python',
  'JavaScript',
  'HTML',
  'CSS',
  'SQL',
  'Excel',
  'Photoshop',
  'React',
  'Node.js',
  'Public Speaking',
  'Writing',
  'Project Management',
  'Data Analysis',
  'Marketing',
  'Photography',
  'Video Editing',
  'Guitar',
  'Piano',
  'French',
  'Spanish',
  'German',
  'Cooking',
  'Baking',
  'Yoga',
  'Fitness',
  'Other'
]; 